global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

remote_write:
  - url: <GRAFANA_INSTANCE_ID>
    basic_auth:
      username: "<instance_id>"
      password: "api_key"
    # opcional: gzip/compression es manejado por prom client, no necesitas setearlo aqu√≠
